name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: "latest"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Run linter
        # for now, only use selene because luau-lsp is not able to ignore the node_modules folder
        run: yarn run lint:selene

      - name: Verify code style
        run: yarn run style-check

      - name: Build assets
        run: yarn run build-assets
